---
kind: pipeline
name: scan-build

node:
  freeswitch: stack

steps:
    - name: scan-build
      image: signalwire/freeswitch-public-base
      pull: true
      commands:
      - apt-get update && apt-get install -y clang-tools-7 libjansson-dev libcjson-dev libcurl-ocaml-dev libjwt-dev uuid-dev
      - autoreconf -i
      - automake --add-missing
      - libtoolize
      - autoreconf
      - ./configure
      - mkdir -p scan-build
      - echo '#!/bin/bash\nscan-build-7 -o ./scan-build/ make -j`nproc --all` |& tee ./scan-build-result.txt\nexitstatus=$${PIPESTATUS[0]}\necho $$exitstatus > ./scan-build-status.txt\n' > scan.sh
      - chmod +x scan.sh
      - ./scan.sh
      - exitstatus=`cat ./scan-build-status.txt`
      - echo "*** Exit status is $exitstatus"
      - make install
      - make check

    - name: notify
      image: signalwire/scan-build-notify
      pull: true
      environment:
        GITHUB_CI_APP_PEM:
          from_secret: github_ci_app_pem
        SSH_KEY:
          from_secret: ssh_key
        SLACK_WEBHOOK_URL:
          from_secret: slack_webhook_url
      commands:
      - /root/notify.sh

      
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
---
kind: signature
hmac: 69c3119bb2c0cbd6bc280d66e595345518749cff85d15cc561a6a1e3bc20c77d

...
